"""No wire name may disappear when the six legacy surfaces are deleted.

Phase 2 collapses ``crypto/legacy/{cli,api_server,mcp_server}.py`` and their equity
counterparts — 15 873 lines writing one capability list out six times — into three thin
projections over :data:`crocodile.core.capability.REGISTRY`. That is the largest deletion
in the project, and it rests on the same claim Phase 1 made about seven shared modules:
that the survivor covers everything the deleted copy did. Phase 1 was wrong seven times
and nothing raised; the queries just came back empty.

``premerge_public_api.json`` measures that claim for Python identifiers. It says nothing
about what a *user* can call. A CLI command, a REST path and an MCP tool name are the
product's actual contract, and every one of them is about to be regenerated by a
projector, so ``premerge_phase2_surface.json`` freezes them while all six surfaces are
still intact — the same discipline, applied to the wire.

Two properties make this gate worth having rather than merely present:

**It does not care how a name is served.** Resolution is against a union of sources — the
legacy files today, the capability registry after the port — so the same assertions hold
across the deletion without the test changing. It is also fork-agnostic: whether a name is
answered for crypto, for equity or for both is the symmetry gate's subject
(``IRREDUCIBLE`` / ``PENDING_SYMMETRY``), not this one's. This gate asks only whether the
name still answers at all.

**Its exemptions carry arguments.** Both ledgers below follow ``IRREDUCIBLE``'s rule: every
entry states the argument, and "we did not port it" is not one.
"""

from __future__ import annotations

import ast
import json
import pathlib
import re
from collections.abc import Iterable
from typing import Any

_REPO = pathlib.Path(__file__).resolve().parents[2]
_SRC = _REPO / "src" / "crocodile"
_FIXTURE = pathlib.Path(__file__).parent / "premerge_phase2_surface.json"

_LEGACY: dict[tuple[str, str], pathlib.Path] = {
    ("crypto", "cli"): _SRC / "crypto" / "legacy" / "cli.py",
    ("crypto", "rest"): _SRC / "crypto" / "legacy" / "api_server.py",
    ("crypto", "mcp"): _SRC / "crypto" / "legacy" / "mcp_server.py",
    ("equity", "cli"): _SRC / "equity" / "legacy" / "cli.py",
    ("equity", "rest"): _SRC / "equity" / "legacy" / "api_server.py",
    ("equity", "mcp"): _SRC / "equity" / "legacy" / "mcp_server.py",
}

_REQUIRED = "<required>"
"""Marker for a parameter with no default, so it is distinguishable from ``default=None``."""

_INJECTED = {"Request", "Response", "BackgroundTasks", "WebSocket"}
"""FastAPI injects these by type. They carry no wire name and are not part of the contract."""


# ---------------------------------------------------------------------------
# Infrastructure: on the wire, but not capabilities
# ---------------------------------------------------------------------------

_INFRASTRUCTURE: dict[str, str] = {
    "/": "Serves the x402 demo dashboard's HTML. A page, not a query.",
    "docs": "Swagger UI for whatever routes exist. It describes the surface; it is not on it.",
    "health": "Liveness probe. Answers whether the process is up, not a question about a market.",
    "status": "Declared in the source as an alias of `health` and returning the same body.",
    "ready": "The same body as `health` with a 503 when the lake is unreachable, for k8s.",
    "version": "Returns `crocodile.__version__`. A property of the build, not of any market.",
    "metrics": "Prometheus exposition of request counters, RSS and uptime — process telemetry.",
    "events": (
        "`GET /api/events` is an SSE heartbeat whose ticks are `round(2000 + random.random() "
        "* 100, 2)`. It emits invented numbers to animate the demo dashboard; there is no "
        "capability behind it to preserve, and porting it would mean porting the fabrication."
    ),
    "simulate-payment": (
        "x402 scaffolding: marks a payment id paid and mints a mock signature, and refuses "
        "unless ALLOW_SIMULATION=true. It exercises the payment gate, it does not serve data."
    ),
    "admin-payments": (
        "Dumps the payments table behind ADMIN_API_KEY, `include_in_schema=False`. Billing "
        "administration for the x402 gate."
    ),
    "mcp": "Launcher: starts the MCP server on stdio. The tools it then serves are the surface.",
    "api": "Launcher: binds the REST server to --host/--port. Same relationship.",
    "update": "Self-update via pip. Acts on the installation, not on market data.",
    "shell": "Starts the interactive REPL that dispatches the other commands.",
    "migrate-lake": (
        "Renames `exchange=` and `provider=` partition directories to `source=` without "
        "opening a Parquet file. `crocodile.capabilities.ops._why_migrate_lake_is_"
        "infrastructure` is the long form and was written by the batch that declined to "
        "declare it: no asset class, because it renames both legacy prefixes in one pass "
        "over one lake; no parameter schema, because its only input is the lake root; and "
        "no honest `prov`, because all four levels are false statements about a directory "
        "that moved. It is hand-written in `surfaces/operate.py`, and now covers both "
        "prefixes rather than only crypto's, which closes the asymmetry that argument ends "
        "on."
    ),
    "capabilities": (
        "Reclassified here at Phase 2's exit, against this list's own prior note, and the "
        "argument that moved it is the registry's own vocabulary rather than the "
        "product/process axis. Judged the way `migrate-lake` was judged in the same merge, "
        "it fails all three tests: no asset class, an empty parameter schema, and no "
        "provenance — `NATIVE` would claim a venue reported the list, `DERIVED` that it was "
        "computed from records, `SYNTHETIC` that it was modelled, `UNAVAILABLE` that it is "
        "a typed hole, and it is a list of the names this build answers to. A provenance "
        "chosen because the field is required is the first decorative provenance in the "
        "tree, which is exactly the reason `migrate-lake` is not declared either.\n\n"
        "The prior note's objection was not that the classification was wrong but that it "
        "'would license deleting the one route whose whole job is saying what exists'. That "
        "is an argument about a licence, and it is answered by a test rather than by a "
        "classification: `tests/surfaces/test_operational_routes.py` asserts the route is "
        "served, that its `rest` list is exactly what the app mounts, and that its "
        "`mcp_tools_hint` equals `mcp.tool_names()` — which is a stronger guarantee than "
        "this gate ever gave it, because this gate only ever asked whether the *name* "
        "answered and could not have caught the drift that made the old route wrong."
    ),
    "flowmap": "Launcher: opens the PyQt6 flowmap window. A GUI entry point, not a query.",
    "gas-tracker": (
        "Launcher: opens the PyQt6 gas-tracker window and takes no parameters. Note "
        "`IRREDUCIBLE['gas-tracker']` names the *gas-market data* as a capability with no "
        "equity analogue; that is not this entry. If a `gas-tracker` capability is ever "
        "registered, this exemption becomes inert rather than wrong — and "
        "`test_the_infrastructure_list_is_not_hoarding_entries` fails until it is removed."
    ),
}
"""Wire entries that exist but are not capabilities, each with the argument for why.

``capabilities`` was deliberately **not** here until Phase 2's exit, on the argument that it
answers a question about the *product* rather than the *process* and that dropping it would
lose the route an agent calls first. Both halves of that were right and neither was the
question: what it is not is a capability, by the same three tests ``migrate-lake`` was
judged under, and what keeps a route alive is a test rather than a classification. Its entry
above carries the whole reasoning, and ``tests/surfaces/test_operational_routes.py`` carries
the guarantee. The route is still served, and is now derived from :data:`REGISTRY` rather
than hand-copied beside it — which is what fixes the drift that prompted the original note
(``_CAPABILITIES_MCP_TOOLS_HINT`` named 36 tools while ``TOOLS`` declared 37, so
``list_all_exchanges`` existed and the self-description did not mention it).
"""

_INFRASTRUCTURE_AS_SHIPPED: frozenset[str] = frozenset(
    {
        "/",
        "admin-payments",
        "api",
        "capabilities",
        "docs",
        "events",
        "flowmap",
        "gas-tracker",
        "health",
        "mcp",
        "metrics",
        "migrate-lake",
        "ready",
        "shell",
        "simulate-payment",
        "status",
        "update",
        "version",
    }
)
"""The eighteen names above, written out a second time, because this ledger may only shrink.

Not redundancy: a *pin*. ``_INFRASTRUCTURE`` is a claim about the past — *this was never a
capability* — and an exit review showed the dict alone could not tell that claim apart from
its opposite. Deleting the ``catalog-dates`` declaration and adding its two canonical wire
names to the dict above passed all 689 conformance tests, because every rule the dict had
was one a freshly deleted capability satisfies by construction (see
:func:`test_the_infrastructure_list_cannot_grow_to_excuse_a_deleted_capability`).

Growing the list is therefore an edit to two places with a failing test in between, and the
test says what the second edit is admitting to. Shrinking it stays free in one direction
only — when the name became a declared capability, which
:func:`test_the_infrastructure_list_is_not_hoarding_entries` already forces.
"""


# ---------------------------------------------------------------------------
# The rename ledger. Every entry is an argument, not a mapping.
# ---------------------------------------------------------------------------

_NAME_RENAMES: dict[str, tuple[str, str]] = {
    "get-funding-apr": (
        "funding-apr",
        "One capability under three spellings: the CLI command `funding-apr`, the route "
        "`GET /api/v1/funding-apr` and the MCP tool `get_funding_apr` all take a perpetual "
        "symbol and a time range and return per-event funding APR from the same lake query. "
        "The `get_` prefix is an MCP naming habit, not a second capability; `Capability.name` "
        "is one string for all three surfaces, so the prefix has to resolve away somewhere.",
    ),
    # ---------------------------------------------------------------------
    # MCP's verb prefix. Nineteen entries, one argument, stated once here and
    # referred to by each.
    # ---------------------------------------------------------------------
    # `get_funding_apr` above is the first of these and carries the reasoning: MCP tool
    # names were written as verb phrases because a tool is something an agent *does*, while
    # `Capability.name` is one string for all three surfaces and a REST path segment cannot
    # be a verb phrase. Each entry below is the same fact for one more tool, and each was
    # checked rather than pattern-matched — `_mechanical_name` deliberately does not strip
    # the prefix, because two of these do not resolve the way the spelling suggests:
    # `list_all_exchanges` is `markets`, not `list-exchanges`, and `get_spot_perp_basis` is
    # `basis`, not `perp-basis`. A mechanical rule would have silently equated both pairs
    # with the wrong capability, which is a rename that loses a capability while reading
    # green — the exact failure this gate exists for.
    "calculate-ofi": (
        "ofi",
        "Same inputs (symbol, range, interval) and the same per-bin imbalance from the same "
        "lake query as the `ofi` command and the `GET /api/v1/ofi` route.",
    ),
    "detect-mev-sandwiches": (
        "mev-sandwich",
        "Both take a trade sequence and return the legs flagged as a sandwich; the tool "
        "spelling is plural because it names the act of detecting rather than the pattern.",
    ),
    "estimate-slippage": (
        "slippage",
        "Takes symbol, side and size and walks the stored book, which is what the `slippage` "
        "command and route do. Note this makes three spellings for one capability — with "
        "`simulate-price-impact` below — and the registry already carries that one as an "
        "alias, so only this one needed an entry.",
    ),
    "get-chaos-score": (
        "chaos-score",
        "The same four supplied readings and the same [0, 100] composite; the tool takes no "
        "lake and neither does the command.",
    ),
    "get-funding-prediction": (
        "funding-predict",
        "One capability whose two spellings differ in more than the prefix: the tool says "
        "`prediction` and the command says `predict`. Same `rates` and `window_size` inputs "
        "and the same forecast, so it is a naming habit twice over, not a second thing.",
    ),
    "get-indicators": ("indicators", "Same symbol, range, interval, indicator and period."),
    "get-iv-surface": ("iv-surface", "Same underlying and instant; same cross-section."),
    "get-lending-stress": (
        "lending-stress",
        "Same four supplied position numbers and the same health factor before and after "
        "the haircut.",
    ),
    "get-liquidity-depth": (
        "liquidity-depth",
        "Same symbol; same bid and ask size within 1, 2 and 5 percent of mid.",
    ),
    "get-open-interest": (
        "open-interest",
        "Same symbol filter and range, and the same cross-venue forward-filled aggregate.",
    ),
    "get-peg-deviation": (
        "peg-deviation",
        "Same price, threshold and target; same deviation from the peg.",
    ),
    "get-perp-basis": (
        "perp-basis",
        "Same perpetual symbol and range; mark against index per ticker update.",
    ),
    "get-risk-reversal": (
        "risk-reversal",
        "Same underlying, expiry, instant, rate and target delta; same risk reversal and "
        "butterfly off the skew.",
    ),
    "get-sequencer-latency": (
        "sequencer-latency",
        "Same exchange; same block-production intervals and ingestion delay.",
    ),
    "get-spot-future-basis": (
        "spot-future-basis",
        "Same future, spot, range and expiry; the same ASOF join.",
    ),
    "get-spot-perp-basis": (
        "basis",
        "The one entry here whose target is not the tool's name with the verb removed. The "
        "tool takes `spot_symbol` and `perp_symbol`, which is exactly `basis`'s parameter "
        "pair and exactly what `GET /api/v1/basis` and the `basis` command take. "
        "`perp-basis` is a *different* capability — mark against index for one contract, no "
        "spot leg — and stripping `get_` mechanically would have folded this into it and "
        "lost the spot-perp join while the gate stayed green.",
    ),
    "get-term-structure": (
        "term-structure",
        "Same underlying, instant and rate; the same ATM term structure.",
    ),
    "get-vol-skew": (
        "vol-skew",
        "Same underlying, expiry, instant and rate; the same per-strike IV and delta.",
    ),
    "list-all-exchanges": (
        "markets",
        "The second entry whose target is not the obvious one. The tool's own docstring says "
        "'Mirrors CLI `markets`' and it returns native connectors, ccxt venues and their "
        "union — which is `markets`' summary word for word. `list-exchanges` is the "
        "*registry* of hand-written connectors and is what `list_registered_exchanges` "
        "below resolves to; the two answer different questions and the difference is the "
        "ccxt venues.",
    ),
    "list-registered-exchanges": (
        "list-exchanges",
        "Both return `crocodile.crypto.exchanges.factory.list_exchanges()` and neither "
        "touches the lake or the network. The MCP spelling says `registered` because that "
        "tool sits next to `list_exchanges_on_disk`, which is the lake-side question and is "
        "already an alias of `catalog-exchanges`.",
    ),
    "smart-money-summary": (
        "smart-money",
        "Same transfers and watchlist in, same capital-flow summary out; `summary` describes "
        "the return shape rather than a second capability.",
    ),
    "track-whale-alerts": (
        "whale-alerts",
        "Same symbol, range and USD threshold; the same trades and liquidations over it.",
    ),
    "get-onchain-price": (
        "onchain-price",
        "The same verb prefix once more. Declared at Phase 2's exit rather than ported with "
        "the other 47 — see `crocodile.capabilities.onchain` — which is why this entry "
        "exists at all.",
    ),
    "get-base-market-data": (
        "base-market-data",
        "Same again. Kept distinct from `onchain-price` because it additionally scans ~1 800 "
        "blocks of swap logs, which is a different cost and was a different tool.",
    ),
    "market-data": (
        "onchain-price",
        "The equity fork's `GET /api/v1/market-data`, whose handler was 380 lines of x402 "
        "payment gate wrapped around one call to `get_onchain_price(symbol)`. The payment "
        "gate is the surface's business — the two routes that administer its ledger are on "
        "`_INFRASTRUCTURE` for that reason — and the answer behind it is this capability. "
        "Note it was served under this name on the *equity* surface while reading a Base "
        "DEX pool; that the name resolves crypto-ward is the fork residue, not the rename.",
    ),
    "simulate-price-impact": (
        "slippage",
        "`GET /api/v1/slippage` and `POST /api/v1/simulate-price-impact` walk the same stored "
        "book for the same answer; the POST exists because it accepts a body, not because it "
        "measures something else. `simulate-price-impact` is the only spelling equity ever "
        "exposed, which is evidence about equity having almost no surface rather than about "
        "the name. Already settled in the registry: `slippage` names the measurement and "
        "carries `simulate-price-impact` in `aliases`.",
    ),
    "catalog-search": (
        "search",
        "`GET /api/v1/catalog/search` and the MCP tool `search_symbols` take the same four "
        "inputs — `q`, `channel`, `exchange`, `limit` — and return the same ranked rows from "
        "the same inventory. The path put it under `catalog/` because it sat beside the "
        "seven other `catalog/*` routes; the registry spells the family with a hyphen "
        "(`catalog-symbols`, `catalog-dates`) and this one is not part of it — it searches "
        "the inventory rather than listing a partition, which is why the CLI always called "
        "it `search` and why `search_symbols` is already an alias.",
    ),
    "exchanges": (
        "list-exchanges",
        "`GET /api/v1/exchanges` returns `list_exchanges()` from the factory registry and "
        "says so in its own docstring, which is the whole of `list-exchanges`. The bare "
        "path was the only spelling REST had; the CLI command and the registry both say "
        "`list-exchanges`, which distinguishes it from `catalog-exchanges` — the partitions "
        "actually on disk — in a way the bare word does not.",
    ),
}
"""Wire name a surface exposed → (the one capability it is, the argument that it is one).

Keys are in the form :func:`_mechanical_name` produces: a REST entry has already lost its
method and ``/api/v1/`` prefix, and every name is lowercased with ``_`` folded to ``-``. So
a purely decorative difference — ``GET /api/v1/x`` against the command ``x`` — needs no
entry, and this ledger holds only the cases where the two spellings are different words.
"""

_PARAM_RENAMES: dict[tuple[str | None, str], tuple[str, str]] = {
    (None, "from"): (
        "start_ns",
        "The forks' own equivalence, not one imposed here: `backfill` declares "
        '`typer.Option("--from", "--start")` as one option with two spellings, and documents '
        "both as nanoseconds UTC. The registry spells it `start_ns` because a bare `start` "
        "does not say what unit it is in, and every one of these is nanoseconds.",
    ),
    (None, "start"): ("start_ns", "Same option as `--from`; see above."),
    (None, "to"): (
        "end_ns",
        'The other half of the same declaration: `typer.Option("--to", "--end")`.',
    ),
    (None, "end"): ("end_ns", "Same option as `--to`; see above."),
    (None, "expiry"): (
        "expiry_ns",
        "The same pattern once more: `vol-skew` and `risk-reversal` declare "
        '`typer.Option("--expiry-ns", "--expiry")` as one option, and REST and MCP expose '
        "only `expiry_ns`. Unit-suffixed for the same reason as `start_ns`.",
    ),
    ("slippage", "amount"): (
        "size",
        "`PriceImpactPayload` accepts both and the handler's first line is "
        "`size = payload.size if payload.size is not None else payload.amount` — a "
        "body-level alias for one quantity, written into the fork rather than into a schema. "
        "One name for one quantity, and `size` is the one the registry's SlippageParams uses.",
    ),
    (None, "at"): (
        "at_ns",
        "The third instance of the unit-suffix pattern `--from`/`--to` set. `iv-surface`, "
        "`term-structure`, `vol-skew` and `risk-reversal` each take `--at` on the CLI and "
        "`at` on REST and MCP, documented as nanoseconds UTC, and the registry spells it "
        "`at_ns` because a bare `at` does not say what unit it is in.",
    ),
    ("backfill", "exchange"): (
        "source",
        "The merged partition key. Crypto lakes wrote `exchange={venue}/` and equity lakes "
        "`provider={name}/`; both are `source={name}/` now, and one `backfill` command "
        "serving both markets cannot call the same slot by the losing name of either fork.",
    ),
    ("collect", "exchange"): ("sources", "Same key as `backfill --exchange`; plural because "
        "`collect` always accepted the flag repeatedly to subscribe to several venues."),
    ("collect", "provider"): ("sources", "The equity fork's spelling of the same key; see "
        "`backfill --exchange`. That the two forks called one slot `exchange` and `provider` "
        "is the whole reason the partition key was merged."),
    ("collect-market", "exchange"): ("sources", "Same as `collect --exchange`."),
    ("collect", "dlq_report"): (
        "dlq_report_path",
        "Both name a file to write the dead-letter report to; the registry suffixes it "
        "`_path` for the same reason it suffixes `_ns` — the bare name reads as a boolean.",
    ),
    ("collect-market", "dlq_report"): ("dlq_report_path", "Same option; see `collect`."),
    ("collect-market", "all"): (
        "all_symbols",
        "`--all` meant 'every symbol in the venue's universe', next to `--top N` which means "
        "'the busiest N'. A bare `all` beside `top` and `quote` does not say all *what*.",
    ),
    ("collect-market", "kind"): (
        "kinds",
        "Declared repeatable on the CLI — `--kind spot --kind perp` — so it selected a set "
        "from the start, and REST took it comma-separated. Plural is what it always was.",
    ),
    ("universe", "kind"): ("kinds", "The same repeatable option on the same instrument "
        "kinds; see `collect-market --kind`."),
    ("census", "venue"): (
        "venues",
        "Repeatable on the CLI for the same reason: a census over several venues is the "
        "normal call, and the singular spelling described one flag rather than one venue.",
    ),
    ("funding-predict", "window"): (
        "window_size",
        "The rolling window the forecast averages over. MCP already spelled it "
        "`window_size`; the CLI's `--window` is the same integer and the same average.",
    ),
    ("basis", "spot"): (
        "spot_symbol",
        "REST and MCP already spelled both legs `spot_symbol`/`perp_symbol`; only the CLI "
        "shortened them, and a bare `--spot` beside `--perp` and `--future` reads as a mode "
        "flag rather than as the symbol it takes.",
    ),
    ("basis", "perp"): ("perp_symbol", "The other leg of the same pair; see `basis --spot`."),
    ("spot-future-basis", "spot"): ("spot_symbol", "Same pair, other capability."),
    ("spot-future-basis", "future"): ("future_symbol", "Same pair, other capability."),
    ("perp-basis", "perp_symbol"): (
        "symbol",
        "`perp-basis` compares one contract's mark against its own index, so there is only "
        "one symbol and nothing for the qualifier to distinguish it from. The qualifier is "
        "load-bearing on `basis` and `spot-future-basis`, which take two.",
    ),
    ("catalog-scan", "symbol"): (
        "symbols",
        "`GET /api/v1/catalog/scan?symbol=` was documented as comma-separated and the CLI's "
        "`--symbols` was already plural, so the route's singular spelling was the odd one "
        "out rather than a narrower parameter.",
    ),
    ("resample", "fill"): (
        "fill_empty",
        "The equity CLI's `--fill` and its own `--fill-empty` on `indicators` are one flag: "
        "both are passed straight to `client.resample(..., fill_empty=)`. The longer "
        "spelling wins because `fill` alone does not say fill *what*.",
    ),
    ("open-interest", "symbol"): (
        "symbols",
        "The CLI's `--symbol` is documented as a *substring filter* — 'e.g. BTC. Omit to "
        "aggregate all' — over an aggregate across exchanges, while REST and MCP take "
        "`symbols` as a comma-separated list. Both select a set from one aggregation; the "
        "singular spelling describes how you name the set, not a different capability. "
        "Scoped to `open-interest` on purpose: elsewhere `--symbol` really is one symbol "
        "(`slippage`, `liquidity-depth`), and folding those into a plural would erase the "
        "distinction rather than record it.",
    ),
}
"""(capability or ``None`` for any, parameter as frozen) → (the one parameter it is, why).

Parameter names are compared lowercased with ``-`` folded to ``_`` and any leading ``--``
stripped, so ``--min-usd`` and ``min_usd`` need no entry.
"""

_PARAM_BECAME_A_CAPABILITY: dict[tuple[str, str], tuple[str, str]] = {
    ("catalog", "symbols"): (
        "catalog-symbols",
        "A second capability wearing a boolean. `catalog --symbols` did not narrow the "
        "channel listing; it *replaced* it, printing the lake's distinct symbols instead — "
        "which is `catalog-symbols`, a command the same CLI already had. One flag selecting "
        "between two measurements is the multiplexer shape this port is undoing, and the "
        "flag cannot survive as a parameter because there is no parameter it corresponds "
        "to: the answer it selected is a capability of its own.",
    ),
    ("basis", "future"): (
        "spot-future-basis",
        "The crypto CLI's `basis` was three measurements behind one command, selected by "
        "which pair of legs you named: `--spot --perp` is spot against perpetual mark, "
        "`--perp` alone is mark against index, `--spot --future --expiry` is spot against a "
        "dated future. The registry split them into `basis`, `perp-basis` and "
        "`spot-future-basis`, which is why REST already served all three on separate paths. "
        "`--future` names the far leg of the third one and is its `future_symbol`.",
    ),
    ("basis", "expiry_ns"): (
        "spot-future-basis",
        "The other half of the same mode: a dated future has an expiry and the other two "
        "measurements have nothing to put in it. It is `spot-future-basis`'s `expiry_ns`.",
    ),
    ("indicators", "fill_empty"): (
        "resample",
        "The equity `indicators` command resampled the bars and *then* applied the "
        "indicator, and `--fill-empty` governed the first step — its body passes the flag "
        "to `client.resample(...)` and nothing else reads it. Resampling is its own "
        "capability, and the flag went with the step it belongs to rather than staying on "
        "a command that no longer performs it.",
    ),
}
"""(capability, parameter as frozen) → (the capability that now accepts it, why).

A fourth shape the two rename ledgers cannot express: the parameter did not vanish and was
not renamed, it moved to a *sibling* capability, because the command that carried it was
doing two things. Given its own ledger rather than folded into ``_AMBIENT_PARAMETERS``
because the claims are opposite — an ambient parameter is one no capability should carry,
and every one of these is carried by a capability that is named right here and asserted to
be reachable. That assertion is what makes this stricter than an exemption rather than
looser: ``test_a_parameter_that_moved_landed_somewhere_reachable`` fails if the named
capability is not served on the surface the parameter was frozen on.
"""

_AMBIENT_PARAMETERS: dict[str, str] = {
    "output": (
        "Where to write the answer, which is the surface's question and not the "
        "measurement's. `census --output FILE` wrote the same census the command otherwise "
        "printed; a REST caller redirects a response body and an MCP caller does not have "
        "the concept. Carrying it would put a filesystem path in the schema all three "
        "surfaces publish."
    ),
    "json": (
        "How to render, not what to ask. `census --json` printed the same object as a JSON "
        "document instead of a table — which is what REST and MCP do unconditionally, and "
        "what `ReturnKind` already tells the CLI."
    ),
    "symbols_only": (
        "The same rendering question in the other direction: `universe --symbols-only` "
        "printed one column of the rows the command already returned. A caller selects "
        "columns from a result; it does not ask the venue a different question."
    ),
    "file": (
        "Reading the input off disk rather than being given it. `funding-predict --file` "
        "loaded a rate history from a CSV and handed it to the same forecast `--rates` "
        "feeds; `FundingPredictParams.rates` is the parameter, and a path is how one "
        "surface out of three happened to obtain it. A path in the shared schema is also a "
        "path a network caller would be asking the *server* to open."
    ),
    "gas_file": ("The same, for `gas-vol`'s gas series; the parameter is `gas`."),
    "vol_file": ("The same, for `gas-vol`'s volatility series; the parameter is `vol`."),
    "persist": (
        "Whether reading the ladder also writes it into the lake — a decision about what "
        "*this surface* is allowed to do, which is why it sits beside `readonly` on "
        "`CapabilityContext` rather than in a schema. As a parameter it would let a caller "
        "of the network surfaces turn a GET into a write, and both of them are readonly by "
        "construction; the capability that puts records in the lake is `collect`."
    ),
    "no_persist": ("The other half of the same boolean pair; see `persist`."),
    "data_dir": (
        "Where the lake is, not what to ask it. Every lake-touching command carries "
        "`--data-dir`; it is deployment configuration, and `Settings` is now the one place "
        "that resolves it, so a projection serves it once for the whole surface instead of "
        "48 times."
    ),
    "limit": (
        "A cap on how much of the answer comes back, applied uniformly by the REST surface "
        "(every route clamps to 10 000) and not by the measurement. Which rows exist is the "
        "capability's business; how many are returned in one response is the surface's."
    ),
    "payment_signature": (
        "The x402 payment proof, carried as a header. It authenticates the call rather than "
        "describing what is being asked."
    ),
}
"""Parameters that belong to a surface or a deployment rather than to a capability."""


# ---------------------------------------------------------------------------
# Scanning the surfaces. AST, never import.
# ---------------------------------------------------------------------------
#
# The fixture was generated with these same functions, so the frozen side and the live side
# cannot disagree about what "a command" or "a route" is. Parsing rather than importing is
# the point: an import-time registry is exactly what Phase 2 replaces, and an inventory
# derived from it would move whenever it moves.


def _literal(node: ast.AST | None) -> Any:
    """The default as data where it is data, and as source text where it is not."""
    if node is None:
        return _REQUIRED
    try:
        value = ast.literal_eval(node)
    except Exception:
        return ast.unparse(node)
    if isinstance(value, (str, int, float, bool, dict)) or value is None:
        return value
    if isinstance(value, (list, tuple)):
        return list(value)
    return ast.unparse(node)


def _annotation_name(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _defaults(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> dict[str, ast.AST | None]:
    out: dict[str, ast.AST | None] = {}
    positional = fn.args.posonlyargs + fn.args.args
    pad = len(positional) - len(fn.args.defaults)
    for i, arg in enumerate(positional):
        out[arg.arg] = fn.args.defaults[i - pad] if i >= pad else None
    for arg, default in zip(fn.args.kwonlyargs, fn.args.kw_defaults, strict=True):
        out[arg.arg] = default
    return out


def _all_args(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.arg]:
    return fn.args.posonlyargs + fn.args.args + fn.args.kwonlyargs


def _typer_option(node: ast.AST | None, aliases: dict[str, ast.AST]) -> ast.Call | None:
    """The ``typer.Option(...)`` governing a parameter, resolving module-level Annotated aliases.

    Both CLIs hoist ``--data-dir`` into a shared ``_DataDirOpt`` alias, so a scan that only
    looked at inline annotations would miss the most widely used option in the product.
    """
    if isinstance(node, ast.Name) and node.id in aliases:
        node = aliases[node.id]
    if isinstance(node, ast.Subscript) and _annotation_name(node.value) == "Annotated":
        elements = node.slice.elts if isinstance(node.slice, ast.Tuple) else [node.slice]
        for element in elements[1:]:
            if isinstance(element, ast.Call):
                func = element.func
                if (isinstance(func, ast.Attribute) and func.attr == "Option") or (
                    isinstance(func, ast.Name) and func.id == "Option"
                ):
                    return element
    return None


def _flags(option: ast.Call) -> list[str]:
    """Every long spelling declared on one option.

    Typer allows several, either as separate strings (``"--expiry-ns", "--expiry"``) or as a
    boolean pair in one (``"--persist/--no-persist"``). All of them are on the wire.
    """
    out: list[str] = []
    for arg in option.args:
        value = _literal(arg)
        if isinstance(value, str) and value.startswith("-"):
            out.extend(part for part in value.split("/") if part.startswith("--"))
    return out


def scan_cli(path: pathlib.Path) -> dict[str, dict[str, Any]]:
    """Typer command name → its long options and their defaults."""
    tree = ast.parse(path.read_text())
    aliases = {
        node.targets[0].id: node.value
        for node in tree.body
        if isinstance(node, ast.Assign)
        and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
        and isinstance(node.value, ast.Subscript)
    }

    out: dict[str, dict[str, Any]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        command: str | None = None
        for decorator in node.decorator_list:
            if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute):
                if decorator.func.attr == "command":
                    named = next(
                        (_literal(k.value) for k in decorator.keywords if k.arg == "name"), None
                    )
                    # typer.main.get_command_name: lowercase, underscores to dashes.
                    command = (
                        named if isinstance(named, str) else node.name.lower().replace("_", "-")
                    )
            elif isinstance(decorator, ast.Attribute) and decorator.attr == "command":
                command = node.name.lower().replace("_", "-")
        if command is None:
            continue

        defaults = _defaults(node)
        options: dict[str, Any] = {}
        for arg in _all_args(node):
            option = _typer_option(arg.annotation, aliases)
            default = defaults.get(arg.arg)
            if option is None:
                # The pre-Annotated spelling: ``name: T = typer.Option(default, "--flag")``.
                if (
                    isinstance(default, ast.Call)
                    and isinstance(default.func, ast.Attribute)
                    and default.func.attr == "Option"
                ):
                    option = default
                    positional = option.args[0] if option.args else None
                    literal = _literal(positional) if positional is not None else None
                    default = (
                        positional
                        if not (isinstance(literal, str) and literal.startswith("-"))
                        else None
                    )
                else:
                    continue  # a typer.Argument, or a plain parameter: not an option
            for flag in _flags(option) or ["--" + arg.arg.replace("_", "-")]:
                options[flag] = _literal(default)
        out[command] = {"options": dict(sorted(options.items()))}
    return out


def scan_rest(path: pathlib.Path) -> dict[str, dict[str, Any]]:
    """``METHOD /path`` → its query, header and body parameters with defaults."""
    tree = ast.parse(path.read_text())
    models: dict[str, dict[str, Any]] = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and any(
            _annotation_name(base) == "BaseModel" for base in node.bases
        ):
            models[node.name] = {
                stmt.target.id: _literal(stmt.value)
                for stmt in node.body
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)
            }

    out: dict[str, dict[str, Any]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not (
                isinstance(decorator, ast.Call)
                and isinstance(decorator.func, ast.Attribute)
                and decorator.func.attr in {"get", "post", "put", "delete", "patch"}
                and decorator.args
            ):
                continue
            defaults = _defaults(node)
            params: dict[str, Any] = {}
            for arg in _all_args(node):
                annotation = _annotation_name(arg.annotation)
                if annotation in _INJECTED:
                    continue
                if annotation in models:
                    params.update(models[annotation])  # a POST body is its model's fields
                    continue
                default = defaults.get(arg.arg)
                name = arg.arg
                if (
                    isinstance(default, ast.Call)
                    and isinstance(default.func, ast.Name)
                    and default.func.id in {"Query", "Header", "Body", "Path", "Form"}
                ):
                    alias = next(
                        (_literal(k.value) for k in default.keywords if k.arg == "alias"), None
                    )
                    if isinstance(alias, str):
                        name = alias  # the header's wire spelling, not the Python one
                    inner = next(
                        (k.value for k in default.keywords if k.arg == "default"), None
                    ) or (default.args[0] if default.args else None)
                    params[name] = _literal(inner)
                else:
                    params[name] = _literal(default)
            key = f"{decorator.func.attr.upper()} {_literal(decorator.args[0])}"
            out[key] = {"params": dict(sorted(params.items()))}
    return out


def scan_mcp(path: pathlib.Path) -> dict[str, dict[str, Any]]:
    """MCP tool name → its ``inputSchema`` properties and their defaults."""
    out: dict[str, dict[str, Any]] = {}
    for node in ast.parse(path.read_text()).body:
        if not (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "TOOLS"
        ):
            continue
        for element in node.value.elts:
            tool = ast.literal_eval(element)
            schema = tool.get("inputSchema") or {}
            required = set(schema.get("required") or ())
            properties = schema.get("properties") or {}
            out[tool["name"]] = {
                "params": {
                    name: body.get("default", _REQUIRED if name in required else None)
                    for name, body in sorted(properties.items())
                }
            }
    return out


_SCANNERS = {"cli": scan_cli, "rest": scan_rest, "mcp": scan_mcp}


# ---------------------------------------------------------------------------
# Canonicalisation
# ---------------------------------------------------------------------------


def _mechanical_name(kind: str, raw: str) -> str:
    """The wire name with only its surface's own decoration removed.

    A REST entry loses its method and version prefix because ``Capability.name`` *is* the
    path segment — that is the documented projection rule, not a guess about what a route
    might have meant. Nothing else is inferred here: stripping MCP's ``get_`` habit
    mechanically would silently equate names that were never the same capability, so those
    go through :data:`_NAME_RENAMES` one argued entry at a time.
    """
    if kind == "rest":
        path = raw.split(" ", 1)[1]
        path = path.removeprefix("/api/v1/").removeprefix("/api/")
        path = re.sub(r"\{[^}]*\}", "", path).strip("/")
        raw = path.replace("/", "-") or "/"
    return raw.strip().lower().replace("_", "-")


def _canonical_name(kind: str, raw: str) -> str:
    """The one capability a wire entry names, after the rename ledger is consulted."""
    name = _mechanical_name(kind, raw)
    return _NAME_RENAMES.get(name, (name, ""))[0]


def _canonical_param(capability: str, raw: str) -> str:
    param = raw.lstrip("-").strip().lower().replace("-", "_")
    for key in ((capability, param), (None, param)):
        if key in _PARAM_RENAMES:
            return _PARAM_RENAMES[key][0]
    return param


# ---------------------------------------------------------------------------
# What is served today, and what was frozen
# ---------------------------------------------------------------------------


def _served() -> dict[str, dict[str, set[str]]]:
    """Surface kind → capability name → every parameter it accepts, from wherever it is served.

    Two sources, unioned, both optional. The legacy files answer for their own kind today.
    The registry answers for all three kinds, because a projection is derived from it
    mechanically — a name in :data:`REGISTRY` is a command, a route *and* a tool by
    construction, which is the whole premise of Phase 2. Neither source has to exist, so the
    same assertions hold on both sides of the deletion without this file changing.

    Kept per kind rather than pooled: with one pool, deleting the `funding-apr` command would
    stay green on the strength of `GET /api/v1/funding-apr`, and losing a command is losing a
    command. The cost is that a capability already in the registry is *trusted* to be
    projected onto all three surfaces rather than measured — two capabilities today. That
    trust is the projection's own tests to keep, not this gate's; what this gate owns is that
    nothing which was on the wire before Phase 2 falls out of both sources at once.
    """
    served: dict[str, dict[str, set[str]]] = {kind: {} for kind in _SCANNERS}

    def add(kind: str, name: str, params: Iterable[str]) -> None:
        served[kind].setdefault(name, set()).update(_canonical_param(name, p) for p in params)

    for (_fork, kind), path in _LEGACY.items():
        if not path.exists():
            continue
        for raw, body in _SCANNERS[kind](path).items():
            name = _canonical_name(kind, raw)
            add(kind, name, body["options"] if "options" in body else body["params"])

    try:
        from crocodile.core.capability import REGISTRY
    except Exception:  # pragma: no cover - the registry is not optional in practice
        return served

    for capability in REGISTRY.values():
        for spelling in (capability.name, *capability.aliases):
            for surface in _SCANNERS:
                add(
                    surface,
                    _canonical_name("cli", spelling),
                    capability.params.__struct_fields__,
                )
    return served


def _frozen() -> dict[str, dict[str, dict[str, Any]]]:
    raw = json.loads(_FIXTURE.read_text())
    return {fork: kinds for fork, kinds in raw.items() if not fork.startswith("_")}


def _frozen_entries() -> list[tuple[str, str, str, str, dict[str, Any]]]:
    """(fork, kind, raw name, canonical name, parameters) for every frozen entry."""
    return [
        (
            fork,
            kind,
            raw,
            _canonical_name(kind, raw),
            body["options"] if "options" in body else body["params"],
        )
        for fork, kinds in _frozen().items()
        for kind, entries in kinds.items()
        for raw, body in entries.items()
    ]


# ---------------------------------------------------------------------------
# Guard the guard
# ---------------------------------------------------------------------------


def test_the_frozen_surface_is_the_size_it_should_be() -> None:
    """An emptied or truncated fixture would pass every assertion below in silence.

    That is not hypothetical here: two AST gates earlier in this merge went green while
    checking an empty tree. The counts are pinned so that deleting entries to make the gate
    pass fails first, loudly, and names the file it happened to.
    """
    frozen = _frozen()
    assert set(frozen) == {"crypto", "equity"}
    assert {k for kinds in frozen.values() for k in kinds} == {"cli", "rest", "mcp"}

    counts = {(f, k): len(e) for f, kinds in frozen.items() for k, e in kinds.items()}
    assert counts == {
        ("crypto", "cli"): 48,
        ("crypto", "rest"): 48,
        ("crypto", "mcp"): 37,
        ("equity", "cli"): 9,
        ("equity", "rest"): 9,
        ("equity", "mcp"): 5,
    }, f"the six legacy surfaces exposed these counts; found {counts}"

    total = sum(len(params) for *_, params in _frozen_entries())
    assert total == 456, f"the six surfaces declared 456 parameters between them, found {total}"


def test_the_scanners_still_find_the_surfaces_they_are_pointed_at() -> None:
    """A scanner that silently returns nothing is a served-side hole, not a red test.

    While a legacy file is still on disk it must still parse into entries. If it stopped —
    renamed, moved, or a decorator spelling the scan does not recognise — ``_served()`` would
    quietly shrink and the parity assertions would start reporting losses that never
    happened, or worse, the exemption tests would start passing for the wrong reason.
    """
    for (fork, kind), path in _LEGACY.items():
        if path.exists():
            assert _SCANNERS[kind](path), f"{fork}.{kind} exists at {path} but scanned to nothing"


# ---------------------------------------------------------------------------
# The promise Phase 2 is making
# ---------------------------------------------------------------------------


def test_no_wire_name_disappeared() -> None:
    """Every command, route and tool a user could call still answers.

    This is the assertion the deletion is not allowed to proceed without. The three surfaces
    are being regenerated from a registry that today holds two capabilities; the claim that
    the projection covers what six hand-written files covered is exactly the kind of
    superset claim Phase 1 made seven times and got wrong seven times.
    """
    served = _served()
    lost = sorted(
        {
            f"{fork}.{kind} {raw!r} → {name}"
            for fork, kind, raw, name, _params in _frozen_entries()
            if name not in _INFRASTRUCTURE and name not in served[kind]
        }
    )
    assert not lost, (
        f"{len(lost)} wire names that were callable before Phase 2 and are callable nowhere "
        f"now: {lost}. Serve them: a registry entry, or an `aliases` entry for a retired "
        "spelling. _INFRASTRUCTURE is not the remedy for this failure — it records that a "
        "name was *never* a capability, which is a claim about the past, and offering it "
        "here is how an exit review deleted `catalog-dates` and left all 689 conformance "
        "tests green. Adding a name to it now also fails "
        "test_the_infrastructure_list_cannot_grow_to_excuse_a_deleted_capability, which is "
        "the test to read before deciding this name was never a capability."
    )


def test_no_wire_parameter_disappeared() -> None:
    """A command that survives with half its options is a capability that half disappeared.

    The name is the coarse check; this is the one that catches a projection that kept
    `slippage` but dropped `size_unit`, which is the shape the Phase 1 losses actually had —
    the entry point still existed, it just answered with less.
    """
    served = _served()
    lost: list[str] = []
    for fork, kind, raw, name, params in _frozen_entries():
        if name in _INFRASTRUCTURE or name not in served[kind]:
            continue
        for param in params:
            canonical = _canonical_param(name, param)
            if canonical in _AMBIENT_PARAMETERS or (name, canonical) in _PARAM_BECAME_A_CAPABILITY:
                continue
            if canonical not in served[kind][name]:
                lost.append(f"{fork}.{kind} {raw!r} {param!r} → {name}.{canonical}")
    assert not lost, (
        f"{len(lost)} parameters accepted before Phase 2 and accepted nowhere now: "
        f"{sorted(lost)}. Either carry them onto the capability's params struct or add a "
        "justified entry to _PARAM_RENAMES, _PARAM_BECAME_A_CAPABILITY or "
        "_AMBIENT_PARAMETERS."
    )


def test_a_parameter_that_moved_landed_somewhere_reachable() -> None:
    """``_PARAM_BECAME_A_CAPABILITY`` must name a capability that is actually served.

    Without this the ledger would be an exemption list wearing a redirect: "it moved" is
    only a defence if the place it moved to answers. Every entry names a capability, and
    every one of those has to be reachable on the same surface kind the parameter was frozen
    on — which is the property the per-kind resolution above exists to keep.
    """
    served = _served()
    frozen_kinds: dict[str, set[str]] = {}
    for _fork, kind, _raw, name, params in _frozen_entries():
        for param in params:
            frozen_kinds.setdefault(f"{name}.{_canonical_param(name, param)}", set()).add(kind)

    stale: list[str] = []
    for (name, param), (target, why) in _PARAM_BECAME_A_CAPABILITY.items():
        entry = f"_PARAM_BECAME_A_CAPABILITY[{name!r}, {param!r}]"
        assert why.strip(), f"the move of {name}.{param} carries no justification"
        kinds = frozen_kinds.get(f"{name}.{param}")
        if not kinds:
            stale.append(f"{entry}: no surface ever accepted that parameter on {name}")
            continue
        for kind in kinds:
            if target not in served[kind]:
                stale.append(f"{entry} → {target}: not served on the {kind} surface")
    assert not stale, f"parameters recorded as moved with nowhere to have moved to: {stale}"


# ---------------------------------------------------------------------------
# Keeping the exemptions honest
# ---------------------------------------------------------------------------


def test_the_infrastructure_list_is_not_hoarding_entries() -> None:
    """An exemption list is where losses go to be forgotten unless it is kept honest.

    Three ways an entry stops being true: it names something the surfaces never exposed, it
    carries no argument, or the thing it calls infrastructure has since been declared a
    capability. All three mean the entry has to go rather than sit there excusing a name
    nobody is checking.
    """
    frozen_names = {name for *_, name, _params in _frozen_entries()}
    stale = sorted(name for name in _INFRASTRUCTURE if name not in frozen_names)
    assert not stale, f"_INFRASTRUCTURE entries that describe nothing the six surfaces had: {stale}"

    unargued = sorted(name for name, why in _INFRASTRUCTURE.items() if not why.strip())
    assert not unargued, f"_INFRASTRUCTURE entries with no argument: {unargued}"

    from crocodile.core.capability import REGISTRY

    contradicted = sorted(
        name
        for name in _INFRASTRUCTURE
        if name in REGISTRY or any(name in c.aliases for c in REGISTRY.values())
    )
    assert not contradicted, (
        f"these are declared capabilities and cannot also be infrastructure: {contradicted}"
    )


def test_the_infrastructure_list_cannot_grow_to_excuse_a_deleted_capability() -> None:
    """A name that served a capability yesterday cannot become one that never was.

    The hole an exit review walked through, end to end: delete the ``catalog-dates``
    declaration, add ``catalog-dates`` and ``list-dates`` to :data:`_INFRASTRUCTURE`, and
    the whole conformance suite passes. Every gate that could have caught it declined for a
    different reason, and each reason was correct in isolation:

    * Gate 4 compares the three surfaces against ``REGISTRY``, so a capability that leaves
      the registry leaves all three surfaces together and the comparison stays balanced.
    * Gate 2 iterates ``REGISTRY``, so a name that is no longer in it is no longer its
      subject.
    * :func:`test_no_wire_name_disappeared` was satisfied by the new ledger entry — and its
      own failure message recommended exactly that.
    * :func:`test_the_infrastructure_list_is_not_hoarding_entries` asks that the name was on
      the frozen wire, that it carries prose, and that it is **not currently registered**.
      A just-deleted capability satisfies all three by construction; the third is the one
      that inverts, because deletion is what makes it true.

    What none of them could ask is the question this list actually answers, which is about
    the past rather than about today. So the answer is pinned in
    :data:`_INFRASTRUCTURE_AS_SHIPPED` and an addition has to survive being named there.
    """
    added = sorted(set(_INFRASTRUCTURE) - _INFRASTRUCTURE_AS_SHIPPED)
    assert not added, (
        f"_INFRASTRUCTURE grew by {added}. This list means *never a capability*. If one of "
        "these was serving a capability that has since been deleted, the deletion is the "
        "thing to justify — not the name — and it is not justifiable here: restore the "
        "declaration, or serve the name through `aliases`. If it genuinely was never a "
        "capability, add it to _INFRASTRUCTURE_AS_SHIPPED in the same commit, where the "
        "diff shows a reviewer both halves of the claim at once."
    )

    from crocodile.core.capability import REGISTRY

    dropped = sorted(
        name
        for name in _INFRASTRUCTURE_AS_SHIPPED
        if name not in _INFRASTRUCTURE
        and name not in REGISTRY
        and not any(name in cap.aliases for cap in REGISTRY.values())
    )
    assert not dropped, (
        f"{dropped} left _INFRASTRUCTURE without becoming capabilities. The one exit this "
        "list has is being declared — which is what "
        "test_the_infrastructure_list_is_not_hoarding_entries forces — so a name that is on "
        "neither list is a wire name with nothing left saying what happened to it."
    )


def test_the_rename_ledger_is_not_hoarding_entries() -> None:
    """Every rename must still describe two spellings of something that existed.

    A ledger entry whose source name was never on the wire is not recording a decision; it is
    widening the gate for free. Both ends are checked: the losing spelling has to be one the
    six surfaces really exposed, and the winning one has to be somewhere a caller can reach.
    """
    from crocodile.core.capability import REGISTRY

    frozen = _frozen_entries()
    mechanical = {_mechanical_name(kind, raw) for _fork, kind, raw, _name, _params in frozen}
    canonical = {name for *_, name, _params in frozen} | set(REGISTRY)
    stale: list[str] = []

    for source, (target, why) in _NAME_RENAMES.items():
        entry = f"_NAME_RENAMES[{source!r}]"
        if source not in mechanical:
            stale.append(f"{entry}: no surface ever exposed that spelling")
        if target not in canonical:
            stale.append(f"{entry} → {target}: nothing of that name is reachable")
        assert why.strip(), f"the rename of {source} carries no justification"

    frozen_params = {
        (name, param.lstrip("-").lower().replace("-", "_"))
        for *_, name, params in frozen
        for param in params
    }
    reachable_params = {param for _name, param in frozen_params} | {
        field for capability in REGISTRY.values() for field in capability.params.__struct_fields__
    }
    for (capability_name, param), (target, why) in _PARAM_RENAMES.items():
        entry = f"_PARAM_RENAMES[{capability_name!r}, {param!r}]"
        if capability_name is None:
            if not any(p == param for _n, p in frozen_params):
                stale.append(f"{entry}: no surface ever accepted that parameter")
        elif (capability_name, param) not in frozen_params:
            stale.append(f"{entry}: {capability_name} never accepted that parameter")
        if target not in reachable_params:
            stale.append(f"{entry} → {target}: nothing of that name is accepted anywhere")
        assert why.strip(), f"the rename of {param} carries no justification"

    for param, why in _AMBIENT_PARAMETERS.items():
        if not any(p == param for _n, p in frozen_params):
            stale.append(f"_AMBIENT_PARAMETERS[{param!r}]: no surface ever accepted it")
        assert why.strip(), f"the ambient parameter {param} carries no justification"

    assert not stale, f"exemption entries that no longer describe anything: {stale}"
